routes:
  /:
    data: page.home
    template: home

collections:
  /courses/:
    permalink: /course/{slug}/
    filter: tag:course
    template: index
  /school/:
    permalink: /school/{slug}/
    filter: tag:school
    template: index
  /facilitators/:
    permalink: /facilitators/{slug}/
    filter: tag:facilitator
    template: index
  # /:
  #   permalink: /{slug}/
  #   template: index


taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
